all:
	@make 1-1
	@make 1-2
	@make 1-3
	@make 1-4
	@make 1-5
	@make 1-6
	@make 1-7
	@make 1-8
	@make 1-9
	@make 1-10
	@make 1-11
	@make 1-12
	@make 2-1
	@make 2-2
	@make 2-3
	@make 2-4
	@make 2-5
	@make 2-6
	@make 2-7
	@make 2-8
	@make 2-9
	@make 2-10

clean:
	@latexmk -C
	@rm -rf svg-inkscape

1-1:
	@latexmk -shell-escape "1-1"
	@mv "1-1.pdf" pdf/.

1-2:
	@latexmk -shell-escape "1-2.tex"
	@mv "1-2.pdf" pdf/.

1-3:
	@latexmk -shell-escape "1-3.tex"
	@mv "1-3.pdf" pdf/.

1-4:
	@latexmk -shell-escape "1-4.tex"
	@mv "1-4.pdf" pdf/.

1-5:
	@latexmk -shell-escape "1-5.tex"
	@mv "1-5.pdf" pdf/.

1-6:
	@latexmk -shell-escape "1-6.tex"
	@mv "1-6.pdf" pdf/.

1-7:
	@latexmk -shell-escape "1-7.tex"
	@mv "1-7.pdf" pdf/.

1-8:
	@latexmk -shell-escape "1-8.tex"
	@mv "1-8.pdf" pdf/.

1-9:
	@latexmk -shell-escape "1-9.tex"
	@mv "1-9.pdf" pdf/.

1-10:
	@latexmk -shell-escape "1-10.tex"
	@mv "1-10.pdf" pdf/.

1-11:
	@latexmk -shell-escape "1-11.tex"
	@mv "1-11.pdf" pdf/.

1-12:
	@latexmk -shell-escape "1-12.tex"
	@mv "1-12.pdf" pdf/.

2-1:
	@latexmk -shell-escape "2-1.tex"
	@mv "2-1.pdf" pdf/.

2-2:
	@latexmk -shell-escape "2-2.tex"
	@mv "2-2.pdf" pdf/.

2-3:
	@latexmk -shell-escape "2-3.tex"
	@mv "2-3.pdf" pdf/.

2-4:
	@latexmk -shell-escape "2-4.tex"
	@mv "2-4.pdf" pdf/.

2-5:
	@latexmk -shell-escape "2-5.tex"
	@mv "2-5.pdf" pdf/.

2-6:
	@latexmk -shell-escape "2-6.tex"
	@mv "2-6.pdf" pdf/.

2-7:
	@latexmk -shell-escape "2-7.tex"
	@mv "2-7.pdf" pdf/.

2-8:
	@latexmk -shell-escape "2-8.tex"
	@mv "2-8.pdf" pdf/.

2-9:
	@latexmk -shell-escape "2-9.tex"
	@mv "2-9.pdf" pdf/.

2-10:
	@latexmk -shell-escape "2-10.tex"
	@mv "2-10.pdf" pdf/.
