all:
	@make problem-set-1
	@make problem-set-2

problem-set-1:
	@tectonic -o ../../website/problem-sets "problem-set-1.tex"

problem-set-2:
	@tectonic -o ../../website/problem-sets "problem-set-2.tex"
