all:
	@make problem-set-1
	@make problem-set-2
	@make problem-set-3
	@make problem-set-4

problem-set-1:
	@export SOURCE_DATE_EPOCH=1700000000 && tectonic -o ../../website/problem-sets "problem-set-1.tex"

problem-set-2:
	@export SOURCE_DATE_EPOCH=1700000000 && tectonic -o ../../website/problem-sets "problem-set-2.tex"

problem-set-3:
	@export SOURCE_DATE_EPOCH=1700000000 && tectonic -o ../../website/problem-sets "problem-set-3.tex"

problem-set-4:
	@export SOURCE_DATE_EPOCH=1700000000 && tectonic -o ../../website/problem-sets "problem-set-4.tex"
