all:
	@make problem-set-1
	@make problem-set-2

problem-set-1:
	@tectonic -o pdf "problem-set-1.tex"

problem-set-2:
	@tectonic -o pdf "problem-set-2.tex"

clean:
	@$(RM) pdf/*.aux pdf/*.nav pdf/*synctex.gz
