all:
	@make password-manager
	@make secure-messenger
	@make zk-battleship
	@make proverif

password-manager:
	@tectonic -o ../../website/labs "password-manager.tex"

secure-messenger:
	@tectonic -o ../../website/labs "secure-messenger.tex"

zk-battleship:
	@tectonic -o ../../website/labs "zk-battleship.tex"

proverif:
	@tectonic -o ../../website/labs "proverif.tex"
