all:
	@make password-manager
	@make secure-messenger
	@make zk-battleship
	@make proverif
	@make pq-migration

password-manager:
	@export SOURCE_DATE_EPOCH=1700000000 && tectonic -o ../../website/labs "password-manager.tex"

secure-messenger:
	@export SOURCE_DATE_EPOCH=1700000000 && tectonic -o ../../website/labs "secure-messenger.tex"

zk-battleship:
	@export SOURCE_DATE_EPOCH=1700000000 && tectonic -o ../../website/labs "zk-battleship.tex"

proverif:
	@export SOURCE_DATE_EPOCH=1700000000 && tectonic -o ../../website/labs "proverif.tex"

pq-migration:
	@export SOURCE_DATE_EPOCH=1700000000 && tectonic -o ../../website/labs "pq-migration.tex"
